
# Server configuration settings.
# Redstone strengths of 0 or less and 15 or more have no effect.
# Otherwise, even redstone strengths disconnect all players within range,
# while odd redstone strengths disconnect only the nearest player within range.
# Ranges are given in block units.
#A range of 0 disables all effects at that redstone strength.
# A range of -1 gives that redstone strength infinite range.
[server]
	# The range for redstone strengths 1 and 2.
	#Range: -1 ~ 256
	redstoneStrength_1_2_Range = 1
	# The range for redstone strengths 3 and 4.
	#Range: -1 ~ 256
	redstoneStrength_3_4_Range = 2
	# The range for redstone strengths 5 and 6.
	#Range: -1 ~ 256
	redstoneStrength_5_6_Range = 4
	# The range for redstone strengths 7 and 8.
	#Range: -1 ~ 256
	redstoneStrength_7_8_Range = 8
	# The range for redstone strengths 9 and 10.
	#Range: -1 ~ 256
	redstoneStrength_9_10_Range = 16
	# The range for redstone strengths 11 and 12.
	#Range: -1 ~ 256
	redstoneStrength_11_12_Range = 32
	# The range for redstone strengths 13 and 14.
	#Range: -1 ~ 256
	redstoneStrength_13_14_Range = 64

