
#General Config Section
[general]
	#The Application ID of the Discord App to use
	clientID = 873945868301115413
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 13

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Initilizing Exitian: Expert.."
	#The second line of text under the app name
	state = "Loading.."
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[init.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Main Menu"
	#The seconds line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert - %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[main_menu.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[server_list.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[realms_list.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[join_game.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Dimension: %world%"
	#The second line of text under the app name
	state = "Singleplayer"
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[single_player.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% - %players% players"
	#The second line of text under the app name
	state = "Playing online"
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[multi_player.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord
	[[realms.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Exitian:Expert - %mcver%"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "exitian_expert"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Exitian: Expert on %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "modpack_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	[[section.buttons]]
		label = "Exitian: Expert Website"
		url = "https://exitian.ch/modpack"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = "overworld"
		largeImageText = "Overworld"
		smallImageKey = ""
		smallImageText = "%mods% mods"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = "nether"
		largeImageText = "Nether"
		smallImageKey = ""
		smallImageText = "%mods% mods"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = "end"
		largeImageText = "The End"
		smallImageKey = ""
		smallImageText = "%mods% mods"

