
#Here are configs that need reloading to take effect
[general]
	#Enable Creative Tab
	creative_tab = false
	#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
	dispensers = true
	#Creates a creative tab full of filled jars
	jar_tab = false
	#Enables custom Configured config screen
	custom_configured_screen = false
	#Save generated resources to disk in a 'debug' folder in your game directory. Mainly for debug purposes but can be used to generate assets in all wood types for your mods :0
	debug_save_dynamic_pack = false

[blocks]
	planter = true
	clock_block = false
	pedestal = true
	wind_vane = true
	redstone_illuminator = true
	notice_board = false
	crank = true
	jar = true
	faucet = false
	turn_table = true
	spring_launcher = true
	speaker_block = true
	sign_post = true
	hanging_sign = true
	bellows = true
	sconce = true
	sconce_green = false
	cage = true
	item_shelf = false
	sconce_lever = true
	cog_block = false
	globe = true
	hourglass = true
	sack = false
	blackboard = true
	safe = false
	copper_lantern = true
	flute = false
	gold_trapdoor = false
	gold_door = false
	bamboo_spikes = true
	bamboo_spikes_tipped = true
	stone_lamp = true
	end_stone_lamp = true
	blackstone_lamp = true
	deepslate_lamp = true
	checker_block = true
	netherite_door = false
	netherite_trapdoor = false
	pancake = true
	lock_block = false
	flax = true
	rope = true
	rope_arrow = true
	pulley_block = true
	fodder = false
	bomb = false
	crimson_lantern = true
	magma_cream_block = false
	daub = true
	wattle_and_daub = true
	timber_frame = true
	flag = true
	stone_tile = true
	goblet = false
	raked_gravel = true
	statue = true
	iron_gate = true
	feather_block = true
	flint_block = false
	slingshot = true
	shulker_shell = true
	candy = true
	wrench = false
	urn = true
	ash = true
	ash_bricks = true
	antique_ink = true
	doormat = false
	flower_box = true
	blackstone_tile = true
	soap = true
	bubble_blower = false
	globe_sepia = true
	present = false
	stasis = true
	silver_trapdoor = false
	silver_door = false
	lead_trapdoor = false
	lead_door = false
	dispenser_minecart = true

